name: SkillForge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      neo4j:
        image: neo4j:5-community
        env:
          NEO4J_AUTH: neo4j/testpassword
          # THIS LINE INSTALLS THE APOC PLUGIN
          NEO4J_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Initialize Databases
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/skillforge_test
          NEO4J_URI: neo4j://localhost:7687
          NEO4J_USERNAME: neo4j # Changed NEO4J_USER to NEO4J_USERNAME
          NEO4J_PASSWORD: password
        run: python init_db.py

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/skillforge_test
          NEO4J_URI: neo4j://localhost:7687
          NEO4J_USERNAME: neo4j # Changed NEO4J_USER to NEO4J_USERNAME
          NEO4J_PASSWORD: password
          SECRET_KEY: "a-secret-key-for-testing"
          ACCESS_TOKEN_EXPIRE_MINUTES: "30"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest