name: SkillForge CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      neo4j:
        image: neo4j:5-community
        env:
          # This sets the initial password for the 'neo4j' user to 'testpassword'
          NEO4J_AUTH: neo4j/testpassword
        ports:
          - 7687:7687
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use your existing dev-requirements.txt file
          pip install -r dev-requirements.txt

    # The DB Init step only needs the PostgreSQL URL
    - name: Run Database Initialization
      env:
        # Provide ALL database credentials needed by api/database.py
        DATABASE_URL: "postgresql+psycopg://testuser:testpassword@localhost:5432/testdb"
        NEO4J_URI: "neo4j://localhost:7687"
        NEO4J_USERNAME: "neo4j"
        NEO4J_PASSWORD: "testpassword"
      run: python init_db.py

    - name: Run tests
      # Use the exact same credentials defined in the services block
      env:
        DATABASE_URL: "postgresql+psycopg://testuser:testpassword@localhost:5432/testdb"
        NEO4J_URI: "neo4j://localhost:7687"
        NEO4J_USERNAME: "neo4j"         # This must match the user in NEO4J_AUTH
        NEO4J_PASSWORD: "testpassword"  # This must match the password in NEO4J_AUTH
        SECRET_KEY: "a-secret-key-for-testing"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      run: pytest